version: "3.8"

services:
  web:
    container_name: ecommerce-go
    build:
      dockerfile: .image/Dockerfile
      context: .
    ports:
      - ${PORT}:3000
    volumes:
      - ./app:/usr/src/app
    command: air cmd/main.go -b 0.0.0.0
    env_file: .env
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - database-volume:/var/lib/postgresql/data
volumes:
  database-volume: